name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
      - run: |
          cd tshirts
          bash ../.github/workflows/expectfail.sh dotnet run
      - run: |
          cd misaligned
          bash ../.github/workflows/expectfail.sh dotnet run
      - run: |
          cd alerter
          bash ../.github/workflows/expectfail.sh dotnet run
